# Generated by Django 5.1.4 on 2025-01-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_men', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_men',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
    ]
