# Generated by Django 5.1 on 2025-01-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_men', '0002_alter_delivery_men_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_men',
            name='phone',
            field=models.ImageField(blank=True, null=True, upload_to='img_delivery_men/'),
        ),
    ]
