# Generated by Django 5.1.4 on 2025-01-08 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=500)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='img_foods/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_category', to='list_foods.category')),
            ],
        ),
    ]
