# Generated by Django 5.1.4 on 2025-01-09 11:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_foods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('seg', 'Segunda-feira'), ('ter', 'Terça-feira'), ('qua', 'Quarta-feira'), ('qui', 'Quinta-feira'), ('sex', 'Sexta-feira'), ('sab', 'Sábado'), ('dom', 'Domingo')], max_length=3, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Caregoria'},
        ),
        migrations.AlterModelOptions(
            name='foods',
            options={'verbose_name': 'Iten'},
        ),
        migrations.AddField(
            model_name='foods',
            name='close',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AddField(
            model_name='foods',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foods',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='foods',
            name='delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foods',
            name='open',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AddField(
            model_name='foods',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foods',
            name='table',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foods',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='list_foods.diasemana'),
        ),
    ]
