# Generated by Django 5.1.4 on 2025-01-09 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_foods', '0002_diasemana_alter_category_options_alter_foods_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foods',
            options={'verbose_name': 'Item'},
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='close',
            new_name='friday_close',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='open',
            new_name='friday_open',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='day',
        ),
        migrations.AddField(
            model_name='foods',
            name='monday_close',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AddField(
            model_name='foods',
            name='monday_open',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AddField(
            model_name='foods',
            name='saturday_close',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AddField(
            model_name='foods',
            name='saturday_open',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AddField(
            model_name='foods',
            name='sunday_close',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AddField(
            model_name='foods',
            name='sunday_open',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AddField(
            model_name='foods',
            name='thursday_close',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AddField(
            model_name='foods',
            name='thursday_open',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AddField(
            model_name='foods',
            name='tuesday_close',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AddField(
            model_name='foods',
            name='tuesday_open',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AddField(
            model_name='foods',
            name='wednesday_close',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AddField(
            model_name='foods',
            name='wednesday_open',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
    ]
