# Generated by Django 5.1.4 on 2025-01-09 14:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_foods', '0003_alter_foods_options_rename_close_foods_friday_close_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foods',
            old_name='criado_por',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='data_modificacao',
            new_name='modification_date',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='value',
        ),
        migrations.AddField(
            model_name='category',
            name='friday_close',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Sexta fechamento'),
        ),
        migrations.AddField(
            model_name='category',
            name='friday_open',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Sexta abertura'),
        ),
        migrations.AddField(
            model_name='category',
            name='meal_type',
            field=models.CharField(choices=[('padrao', 'Padrão'), ('pizza', 'Pizza')], default='lunch', max_length=10, verbose_name='Modelo da categoria'),
        ),
        migrations.AddField(
            model_name='category',
            name='monday_close',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Segunda fechamento'),
        ),
        migrations.AddField(
            model_name='category',
            name='monday_open',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Segunda abertura'),
        ),
        migrations.AddField(
            model_name='category',
            name='saturday_close',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Sabado fechamento'),
        ),
        migrations.AddField(
            model_name='category',
            name='saturday_open',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Sabado abertura'),
        ),
        migrations.AddField(
            model_name='category',
            name='sunday_close',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Domingo fechamento'),
        ),
        migrations.AddField(
            model_name='category',
            name='sunday_open',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Domingo abertura'),
        ),
        migrations.AddField(
            model_name='category',
            name='thursday_close',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Quinta fechamento'),
        ),
        migrations.AddField(
            model_name='category',
            name='thursday_open',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Quinta abertura'),
        ),
        migrations.AddField(
            model_name='category',
            name='tuesday_close',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Terça fechamento'),
        ),
        migrations.AddField(
            model_name='category',
            name='tuesday_open',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Terça abertura'),
        ),
        migrations.AddField(
            model_name='category',
            name='wednesday_close',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Quarta fechamaneto'),
        ),
        migrations.AddField(
            model_name='category',
            name='wednesday_open',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Quarta abertura'),
        ),
        migrations.AddField(
            model_name='foods',
            name='value_delivery',
            field=models.IntegerField(blank=True, null=True, verbose_name='Preço delivery'),
        ),
        migrations.AddField(
            model_name='foods',
            name='value_table',
            field=models.IntegerField(blank=True, null=True, verbose_name='Preço mesa'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_category', to='list_foods.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='delivery',
            field=models.BooleanField(default=True, verbose_name='Delivery'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='friday_close',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Sexta fechamento'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='friday_open',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Sexta abertura'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='monday_close',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Segunda fechamento'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='monday_open',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Segunda abertura'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='saturday_close',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Sabado fechamento'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='saturday_open',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Sabado abertura'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Pausar'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='sunday_close',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Domingo fechamento'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='sunday_open',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Domingo abertura'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='table',
            field=models.BooleanField(default=False, verbose_name='Mesa'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='thursday_close',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Quinta fechamento'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='thursday_open',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Quinta abertura'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='tuesday_close',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Terça fechamento'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='tuesday_open',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Terça abertura'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='wednesday_close',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Quarta fechamaneto'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='wednesday_open',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Quarta abertura'),
        ),
    ]
