# Generated by Django 5.1.4 on 2025-01-09 15:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_foods', '0004_rename_criado_por_foods_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria'},
        ),
        migrations.AlterField(
            model_name='category',
            name='meal_type',
            field=models.CharField(choices=[('padrao', 'Padrão'), ('pizza', 'Pizza')], default='padrao', max_length=10, verbose_name='Modelo da categoria'),
        ),
        migrations.AlterField(
            model_name='category',
            name='saturday_close',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Sábado fechamento'),
        ),
        migrations.AlterField(
            model_name='category',
            name='saturday_open',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Sábado abertura'),
        ),
        migrations.AlterField(
            model_name='category',
            name='wednesday_close',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Quarta fechamento'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foods', to='list_foods.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='saturday_close',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Sábado fechamento'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='saturday_open',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Sábado abertura'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='wednesday_close',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Quarta fechamento'),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Loja')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Endereço')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Última Modificação')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='list_foods.store', verbose_name='Loja'),
            preserve_default=False,
        ),
    ]
