# Generated by Django 5.1.4 on 2025-01-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_foods', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.CharField(max_length=200, verbose_name='Proprietário'),
        ),
    ]
