# Generated by Django 5.1.4 on 2025-01-09 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_foods', '0007_alter_store_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='list_foods.store'),
        ),
    ]
