# Generated by Django 5.1.4 on 2025-01-09 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_foods', '0010_alter_category_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categoria'},
        ),
        migrations.AlterModelOptions(
            name='foods',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Item'},
        ),
    ]
