# Generated by Django 5.1.4 on 2025-01-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_foods', '0013_alter_category_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Pausar'),
        ),
    ]
