# Generated by Django 5.1.5 on 2025-03-19 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_foods', '0015_userweb'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='list_foods.store', verbose_name='Loja'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foods',
            name='value_table',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Preço mesa'),
        ),
    ]
