# Generated by Django 5.1.5 on 2025-03-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_foods', '0017_complements_itencomplement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='complements',
            options={'verbose_name': 'Complemento', 'verbose_name_plural': 'Complementos'},
        ),
        migrations.AlterModelOptions(
            name='foods',
            options={'verbose_name': 'Item (Categoria)', 'verbose_name_plural': 'Itens (Categoria)'},
        ),
        migrations.AlterModelOptions(
            name='itencomplement',
            options={'verbose_name': 'Item (Complementos)', 'verbose_name_plural': 'Itens (Complementos)'},
        ),
        migrations.AlterField(
            model_name='itencomplement',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Descrição'),
        ),
    ]
