# Generated by Django 5.1.5 on 2025-03-24 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_foods', '0018_alter_category_options_alter_complements_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='complement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='foods_complements', to='list_foods.complements', verbose_name='Complemento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itencomplement',
            name='complements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iten_complements', to='list_foods.complements', verbose_name='Complementos'),
        ),
    ]
