# Generated by Django 5.1.5 on 2025-03-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_foods', '0019_foods_complement_alter_itencomplement_complements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foods',
            options={'verbose_name': 'Item para (Categoria)', 'verbose_name_plural': 'Itens para (Categorias)'},
        ),
        migrations.AlterModelOptions(
            name='itencomplement',
            options={'verbose_name': 'Item para (Complementos)', 'verbose_name_plural': 'Itens para (Complementos)'},
        ),
    ]
