# Generated by Django 5.1.4 on 2025-01-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Loja')),
                ('url', models.CharField(max_length=200, verbose_name='Nome da Loja')),
                ('phone', models.CharField(max_length=16, verbose_name='Nome da Loja')),
                ('description', models.TextField(max_length=400, verbose_name='Nome da Loja')),
                ('minimum_order_delivery', models.IntegerField(blank=True, null=True, verbose_name='Pedido minimo entrega*')),
                ('minimum_order_pick_up', models.IntegerField(blank=True, null=True, verbose_name='Pedido minimo retirada*')),
            ],
            options={
                'verbose_name': 'Perfil da loja',
            },
        ),
    ]
