# Generated by Django 5.1.4 on 2025-01-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(max_length=200, verbose_name='Nome da Loja')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='img_store/')),
            ],
            options={
                'verbose_name': 'Layout da loja',
                'verbose_name_plural': 'Layout da loja',
            },
        ),
        migrations.AlterModelOptions(
            name='storeinformation',
            options={'verbose_name': 'Estabelecimento', 'verbose_name_plural': 'Estabelecimento'},
        ),
        migrations.AlterField(
            model_name='storeinformation',
            name='description',
            field=models.TextField(max_length=400, verbose_name='Descrição da loja'),
        ),
        migrations.AlterField(
            model_name='storeinformation',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='Telefone para contato'),
        ),
        migrations.AlterField(
            model_name='storeinformation',
            name='url',
            field=models.CharField(max_length=200, verbose_name='Nome para link'),
        ),
    ]
