# Generated by Django 5.1.4 on 2025-01-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_profile', '0002_storelayout_alter_storeinformation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=20, verbose_name='CEP')),
                ('address', models.CharField(max_length=50, verbose_name='Endereço')),
                ('number', models.CharField(max_length=10, verbose_name='Numero')),
                ('add_ons', models.CharField(max_length=100, verbose_name='Complementos')),
                ('district', models.CharField(max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereço',
            },
        ),
        migrations.AlterField(
            model_name='storelayout',
            name='cor',
            field=models.CharField(max_length=200, verbose_name='Cor'),
        ),
    ]
