# Generated by Django 5.1.4 on 2025-01-10 09:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_profile', '0003_storeaddress_alter_storelayout_cor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerZones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('brt', 'Brasília')], max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreOpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_now', models.BooleanField(verbose_name='Fechar agora?')),
                ('monday_open', models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Segunda abertura')),
                ('monday_close', models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Segunda fechamento')),
                ('tuesday_open', models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Terça abertura')),
                ('tuesday_close', models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Terça fechamento')),
                ('wednesday_open', models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Quarta abertura')),
                ('wednesday_close', models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Quarta fechamento')),
                ('thursday_open', models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Quinta abertura')),
                ('thursday_close', models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Quinta fechamento')),
                ('friday_open', models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Sexta abertura')),
                ('friday_close', models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Sexta fechamento')),
                ('saturday_open', models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Sábado abertura')),
                ('saturday_close', models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Sábado fechamento')),
                ('sunday_open', models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Domingo abertura')),
                ('sunday_close', models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Domingo fechamento')),
                ('TimeZone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuso', to='store_profile.timerzones', verbose_name='Fuso')),
            ],
            options={
                'verbose_name': 'Horario de funcionamento',
                'verbose_name_plural': 'Horario de funcionamento',
            },
        ),
    ]
