# Generated by Django 5.1.4 on 2025-01-10 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_profile', '0004_timerzones_storeopeninghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeopeninghours',
            name='TimeZone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuso', to='store_profile.timerzones', verbose_name='Selecione seu fuso horario'),
        ),
    ]
