# Generated by Django 5.1.4 on 2025-01-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_profile', '0005_alter_storeopeninghours_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreFreightPerKilometer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(blank=True, null=True, verbose_name='Distancia em km até:')),
                ('times', models.IntegerField(blank=True, null=True, verbose_name='Tempo de entrega')),
                ('value', models.IntegerField(blank=True, null=True, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Frete',
                'verbose_name_plural': 'Frete',
            },
        ),
    ]
