# Generated by Django 5.1.4 on 2025-01-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_profile', '0006_storefreightperkilometer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreFreightPerDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cit', models.CharField(max_length=50, verbose_name='Cidade:')),
                ('district', models.CharField(max_length=50, verbose_name='Nome do Bairro:')),
                ('times', models.IntegerField(blank=True, null=True, verbose_name='Tempo de entrega em min:')),
                ('value', models.IntegerField(blank=True, null=True, verbose_name='Valor $:')),
            ],
            options={
                'verbose_name': 'Frete Por Bairro',
                'verbose_name_plural': 'Frete Por Bairro',
            },
        ),
        migrations.AlterModelOptions(
            name='storefreightperkilometer',
            options={'verbose_name': 'Frete Por Kilometro', 'verbose_name_plural': 'Frete Por Kilometro'},
        ),
        migrations.AlterField(
            model_name='storefreightperkilometer',
            name='times',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tempo de entrega em min:'),
        ),
        migrations.AlterField(
            model_name='storefreightperkilometer',
            name='value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor $:'),
        ),
    ]
