# Generated by Django 5.1.4 on 2025-01-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_profile', '0007_storefreightperdistrict_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storefreightperkilometer',
            options={'verbose_name': 'Frete Por Kilômetro', 'verbose_name_plural': 'Frete Por Kilômetro'},
        ),
        migrations.AlterField(
            model_name='storefreightperkilometer',
            name='distance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Distância em km até:'),
        ),
    ]
