# Generated by Django 5.1 on 2025-01-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_profile', '0009_storeaddress_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerzones',
            name='dia',
            field=models.CharField(choices=[('brt', 'Horário de Brasília (BRT)')], max_length=10, unique=True),
        ),
    ]
