# Generated by Django 5.1 on 2025-01-21 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_profile', '0010_alter_timerzones_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeopeninghours',
            name='TimeZone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timerzones', to='store_profile.timerzones', verbose_name='Selecione seu fuso horario:'),
        ),
        migrations.AlterField(
            model_name='storeopeninghours',
            name='close_now',
            field=models.BooleanField(blank=True, null=True, verbose_name='Fechar agora?'),
        ),
    ]
