# Generated by Django 5.1 on 2025-01-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_profile', '0011_alter_storeopeninghours_timezone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeopeninghours',
            name='close_now',
            field=models.BooleanField(default=True, verbose_name='Fechar agora?'),
        ),
    ]
