# Generated by Django 5.1 on 2025-01-21 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_profile', '0012_alter_storeopeninghours_close_now'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='storeopeninghours',
            constraint=models.UniqueConstraint(fields=('created_by',), name='unique_user_store_hours'),
        ),
    ]
