# Generated by Django 5.1 on 2025-01-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_profile', '0013_storeopeninghours_unique_user_store_hours'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='storeopeninghours',
            name='unique_user_store_hours',
        ),
    ]
