# Generated by Django 5.1 on 2025-01-21 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_profile', '0014_remove_storeopeninghours_unique_user_store_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeopeninghours',
            options={'verbose_name': 'Horário de funcionamento', 'verbose_name_plural': 'Horários de funcionamento'},
        ),
        migrations.AlterField(
            model_name='storeopeninghours',
            name='TimeZone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timerzones', to='store_profile.timerzones', verbose_name='Selecione seu fuso horário:'),
        ),
    ]
