# Generated by Django 5.1.5 on 2025-03-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_profile', '0015_alter_storeopeninghours_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storefreightperkilometer',
            options={'verbose_name': 'Frete Por Quilômetro', 'verbose_name_plural': 'Frete Por Quilômetro'},
        ),
        migrations.AlterField(
            model_name='storeopeninghours',
            name='close_now',
            field=models.BooleanField(default=False, verbose_name='Fechar agora?. A loja sera aberta no proximo horario de abertura .'),
        ),
    ]
