# Generated by Django 5.1.5 on 2025-03-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='UserWeb',
        ),
    ]
